image: "python:3"

before_script:
  - pip install -r requirements.txt

services:
  - postgres:latest

variables:
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: postgres

build:
  script:
    - pytest
